<?php
	
?>

<small class="copyright">
	<div id="my_story" data-mage-init='{"rollout": {} }' style="line-height: 2" >

		Друзі, я встановлював Magento локально на свій апарат 6 разів.... 
		<span style="display: none; margin-bottom: 30px;"> Я встановлював пусту, версію з даними, версію 2.2, 
			з composer і без нього. І жодного разу Magento не запрацював. 
			Я після кількох ударів бубном я побачив логін адмінки і loader, який крутився вічно. 
			Адмінка так і не запустилась.
			Щось підказувало, що Magento не кльово працює під Windows.
			Після усіх цих страждань мені довелось запустити дроплет на Digital Ocean під Ubuntu і поставити Magento на ньому. Вже
			не сваріться, що не на локальній машині, не хотів зносити Windows.<br />
		</span>

		<button class="action primary"> Показати всю історію </button>
	</div>
</small>
