<?php
	
?>

<small class="copyright">
	<div id="my_story" data-mage-init='{"rollout": {} }' style="line-height: 2" >

		Друзі, я встановлював Magento локально на свій апарат 6 разів.... 
		<span style="display: none; margin-bottom: 30px;"> Я встановлював пусту версію, версію з даними, версію 2.2. 
			З composer і без нього. І жодного разу Magento не запрацював. 
			Максимум, що я побачив - логін адмінки і loader, який крутився вічно. 
			Мабуть Magento не кльово працює під Windows.
			Тому я поставив його тут. Вже пробачте, що не на локальній машині, не хотів зносити Windows.<br />
		</span>

		<button class="action primary"> Показати всю історію </button>
	</div>
</small>
